services:
  - type: web
    name: knit-rimy-site
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        value: "465"
      - key: SMTP_SECURE
        value: "true"
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: MAIL_TO
        sync: false
      - key: MAIL_FROM
        sync: false
